services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  db-store:
